### ISSUE TITLE
Difficulties with interproscan.

### ISSUE THREAD

**Issue by caleb-collar** [ntoda03/NLGenomeSweeper#1]
The region_interproscan script appears to hang as soon as it starts with, "Running interproscan domain and ORF identification..." printed. "All required software was found." is printed when running NLGenomeSweeper and the interproscan directory is in the PATH variable. The other scripts run flawlessly before the tool gets to interproscan. I am running the tool on a compute cluster.
![image](https://user-images.githubusercontent.com/49846301/83893624-cb965400-a715-11ea-85e0-e82b12127aae.png)
I have a feeling this is a simple issue with the script talking to interproscan, but I have been unable to determine the cause.

**Comment by ntoda03** [comment]
Hi,
Sorry, I didn't see this earlier. Depending on the input files Interproscan can take several hours or more to run. How long was it hanging for? Right now the interproscan status is printed to a log file in 02_domain_identification/NLGenomeSweeper.out What does the log file say? If it would be helpful I could also display the messages on the status of the Interproscan while it's running. The current version of the pipeline includes some changes to how the script manages Interproscan memory usage that should make it more reliable.

**Comment by Xueliang24** [comment]
"Problem: Candidate_sites.with_flanking.fa_chunk_00000 did not run" was an example for these files. Every files did not run which was showed in 02_domain_identification/NLGenomeSweeper.out. Is it related with the genome at scaffold level?
