### ISSUE TITLE
can not find consensus_clusters.NB-ARC-consensus.txt

### ISSUE THREAD

**Issue by aisangekoukou** [ntoda03/NLGenomeSweeper#10]
Dear ntoda03，

I want to identify NBS-LRR genes in my interesting species via the NLGenomeSweeper software, but I got one problem. The software can not find the ./temp/NLGenomeSweeper/01_candidate_identification/genome_search//profiler/consensus_clusters.NB-ARC-consensus.txt file, and the temp dir is my output-dir. Attached is the log file. I would be very grateful if you could solve my problem
[NLGenomeSweeper.err.txt](https://github.com/ntoda03/NLGenomeSweeper/files/8362133/NLGenomeSweeper.err.txt)

**Comment by ntoda03** [comment]
Hi,
The version of MUSCLE isn't compatible. Using the version listed in "Requirements & Installation" in the Readme will fix this.
