### ISSUE TITLE
Can't run NLGenomeSweeper

### ISSUE THREAD

**Issue by TinaNeik339** [ntoda03/NLGenomeSweeper#11]
Hi, I tried running NLGenomeSweeper following the steps given. However, I got the following error message, may I know how do I move on?

(base) tinaneik@Tinas-MacBook-Pro-2 ~ % /Users/tinaneik/opt/anaconda3/envs/NLGenomeSweeper/bin/NLGenomeSweeper -genome /Users/tinaneik/Downloads/Vigsu_genome_LATEST.fa
usage: NLGenomeSweeper [-h] -genome <fasta file> [-consensus <fasta file>]
                       [-overwrite [T/F]] [-outdir <path>] [-t <threads>]

NLGenomeSweeper 
v1.2.4
Written by Nicholas Toda

Description:  Searches a genome for NBS-LRR genes based on the presence
of the NB-ARC domain using the consensus sequence of the Pfam HMM profile 
(PF00931) and can be used with custon domain profiles built for a species 
of interest or related species for greater power. 

Details on how to use the program can be found by running the command "NLGenomeSweeper --help"

For full details see: https://github.com/ntoda03/NLGenomeSweeper
Please report any problems to the github page.

optional arguments:
  -h, --help            show this help message and exit

Required arguments:
  -genome <fasta file>  A genome sequence in fasta format to search.

Input arguments:
  -consensus <fasta file>
                        Also search the genome using a custom NB-ARC consensus sequence(s) (optional).It is not recommended to use this option since species specific consensuses will be created.

Output arguments:
  -overwrite [T/F]      Whether to overwrite output files if they already exist. [Default F]
  -outdir <path>        Path where output directory NLGenomeSweeper will be created. [Default ./]

Program control:
  -t <threads>          The number of threads to use. [Default 1]
Traceback (most recent call last):
  File "/Users/tinaneik/opt/anaconda3/envs/NLGenomeSweeper/bin/NLGenomeSweeper", line 302, in <module>
    main(sys.argv[1:])
  File "/Users/tinaneik/opt/anaconda3/envs/NLGenomeSweeper/bin/NLGenomeSweeper", line 280, in main
    raise Exception( 'ERROR: program output already exists and program is not set to overwrite!')
Exception: ERROR: program output already exists and program is not set to overwrite!
(base) tinaneik@Tinas-MacBook-Pro-2 ~ %

**Comment by ntoda03** [comment]
Hi, 
The output folder already exists so it won't overwrite it by default. You can tell it to overwrite the folder with "-overwrite T" and/or choose a different output folder with -outdir
