### ISSUE TITLE
Deactivating the NLGenomeSweeper Env

### ISSUE THREAD

**Issue by lariver2** [ntoda03/NLGenomeSweeper#12]
Hi there,
Every time I try to activate the NLGenomeSweeper Env I get this error:
NLGenomeSweeper: command not found
The first time I installed the pipeline seemed good, but I never got where to put the input fasta file (DNA seq data or peptide sequence?)
In a second session, I get the above error: NLGenomeSweeper: command not found. Do I need to install/clone NLGenomeSweeper every time I run it?
Hope you can help me.
Best

**Comment by ntoda03** [comment]
Hi,
No, if you go through the whole install process then the next time you only need to activate the environment to use it.
