### ISSUE TITLE
Question about the length of annotated NLRs

### ISSUE THREAD

**Issue by yaoxkkkkk** [ntoda03/NLGenomeSweeper#15]
Hi sir.
I find that the annotated genome sequences are all shorter than 1000bp, is that normal?

Looking forward to your reply.

**Comment by ntoda03** [comment]
Hi,
Yes, the annotations are of the protein domains so they will be relatively short. Or if you mean the whole scaffold sequence that will depend on the quality of the genome assembly because these regions can be difficult to assemble.
