### ISSUE TITLE
 When checking output files after running interproscan domain and ORF identification

### ISSUE THREAD

**Issue by Xueliang24** [ntoda03/NLGenomeSweeper#3]
1. The example is "Problem: Candidate_sites.with_flanking.fa_chunk_00000 did not run." All these files did not run. It showed that "Some sequences did not execute. Retrying..." in 02_domain_identification/NLGenomeSweeper.out. But the progress happened again and repeatedly. May it be related with the genome at scaffold level？

2.A problem always happened：Not enough free memory to run interproscan. 3G mimimum is required.
Only 1571 MB of free memery available. Is free memory available not equal with available memory？ Because my available memory is enough。

Wait for your answer

**Comment by ntoda03** [comment]
Hi

1. Interproscan sometimes doesn't run properly and the program will retry the command but it shouldn't happen repeatedly. It will print "Domain identification complete." if it eventually runs correctly. Can you send the whole log of output for Interproscan? 

2. The program checks free memory when it is running. With the system and other programs running the amount of free memory will not be as high as expected. I'm looking at changing it to allow less memory. I'll let you know when it's done.

**Comment by ntoda03** [comment]
Ok, I think both of the problems were caused by the program not waiting properly for Interproscan to finish. The latest version should fix that. Can you run it and let me know if that fixed the problem?

**Comment by Xueliang24** [comment]
em, I think it might be associated with my server performance. After using another server, the problem disappeared.

thanks for your answering
