### ISSUE TITLE
Methods for constructing custom consensus

### ISSUE THREAD

**Issue by mtmcgowan** [ntoda03/NLGenomeSweeper#4]
Hi Nicholas,

After reviewing your paper, it seems to me that the first pass consensus sequences could have a big impact on the sensitivity of this pipeline. I am interested in using this pipeline for several legume species and am trying to determine whether I should use the default consensus sequences provided or try and construct a set of consensus sequences more specific for this plant family. **Can you provide some context for how you constructed your consensus sequences for _V. vinifera_ and why you used this species in particular?**

**Comment by ntoda03** [comment]
Hi, this was originally part of a project studying a species related to V. vinifera, but for the other species tested it also worked well. The idea behind the first pass is that it doesn't need to be all that thorough and as long as you identify some genes for each class the new consensus sequences it builds will be decently close to the other resistance genes in the species. If you have resistance genes from a closely related species you could always build a new set of consensus sequences to see how that compares. There's a script included for building consensus sequences but it's not really documented at the moment: NLGenomeSweeper/scripts/CustomProfiler.py

**Comment by ntoda03** [comment]
I've added the functionality for building custom sequences so I'm closing this.
