### ISSUE TITLE
InterProScan ftp unreachable

### ISSUE THREAD

**Issue by annabeldekker** [ntoda03/NLGenomeSweeper#5]
Your tool looks very promising! 
I am trying to install your dependencies, but can't reach the ftp link for InterProScan with wget.
Is there another way to install this part? 
Thanks!

**Comment by ntoda03** [comment]
Hi! 
That's weird that it doesn't work. The guide on installing the latest version (including panther) is here
https://interproscan-docs.readthedocs.io/en/latest/HowToDownload.html

**Comment by annabeldekker** [comment]
I'm sorry to being so late on following up on this issue. For now, I'm still stuck, but I believe it's an ftp blocking issue from the security side of our company.. Will keep you posted! If you have any advice on alternative installation of your dependencies let me know :)

**Comment by ntoda03** [comment]
Ok! I don't know what's allowed by your security but if it's just for the ftp and interproscan it's also available on their [github](https://github.com/ebi-pf-team/interproscan/releases/tag/5.51-85.0) or [webpage](https://www.ebi.ac.uk/interpro/download/). 
Yeah, with the integrated panther db it sounds simpler and should still be compatible. As long as they didn't change the format or domain codes the pipeline isn't specific to any version.
