### ISSUE TITLE
Memory issue with step 02-domain_identification

### ISSUE THREAD

**Issue by mtmcgowan** [ntoda03/NLGenomeSweeper#6]
Hi Nicholas,

I'm getting an error on step 02 indicating that Interproscan is running out of memory. I went ahead and monitored the RAM usage during this step and verified that this is not system-level as less than 10Gb of my 32Gb is allocated when this error occurs. I've attached a screenshot of the error for reference. Do you have any ideas for how to fix this?

Thanks, 
Matthew

![NLGS_interproscan_ram_error](https://user-images.githubusercontent.com/17625396/119023710-22ad2d00-b957-11eb-81db-431b5db692af.png)

**Comment by ntoda03** [comment]
Hi Matthew,,

That's a direct check of system memory usage before launching Interproscan. Probably there is a lot of memory that could be used not being detected. I'll sort this out.

**Comment by ntoda03** [comment]
Ok it looks like a formatting issue with tool versions. Can you post the output of 'free -m' and 'cat /proc/meminfo'?

**Comment by mtmcgowan** [comment]
Output is attached in a .txt file.
[mem_issue_test_output.txt](https://github.com/ntoda03/NLGenomeSweeper/files/6524682/mem_issue_test_output.txt)

**Comment by ntoda03** [comment]
Perfect. The latest update should fix the problem. Let me know if that works.
