### ISSUE TITLE
Muscle software version incompatibility

### ISSUE THREAD

**Issue by foxeswithdata** [ntoda03/NLGenomeSweeper#8]
Hello! I got the following error when running the software:

`Invalid command line
Unknown option clw`

Turns out muscle has released a new version (5.1) where the -clw CL argument has been removed. Solved by reinstalling an older version of muscle (3.8.1551 available through conda). Can be avoided by specifying the muscle version during environment creation and package installation:

```
conda create -y -n NLGenomeSweeper -c bioconda -c conda-forge \
    python=3.6 blast muscle=3.8.1551 samtools bedtools hmmer transdecoder openjdk
```

**Comment by ntoda03** [comment]
Thanks! I've updated the README to include that info.
