### ISSUE TITLE
A problem [W::fai_fetch] Reference :- not found in fasta file, return empty sequence

### ISSUE THREAD

**Issue by 1835033964** [ntoda03/NLGenomeSweeper#9]
Hi Nicholas,
Thank you for developing such a nice tool to search for NB-ARC domains.Now I am facing a problem like this,

These are inputs. Both of them print the same output(the screenshot)

NLGenomeSweeper -genome TAIR_TNLs.fa
NLGenomeSweeper -genome pfam_NB-ARC.fa -overwrite T

![65CABF5A9F5ADA0C5C95EED4DA597BD3](https://user-images.githubusercontent.com/88643976/156480429-91abc154-b534-4d4f-90fb-c36508e71030.png)

Then I check the NLGenomeSweeper.err for information,this is the content:

![82570973585B8435E174AFEC9EE81B01](https://user-images.githubusercontent.com/88643976/156480329-88c7ac7a-a804-46ab-9822-3c1de0d6c9f6.png)

Do you have any ideas to  help me to fix the problem. 

Thank you,
Lan

**Comment by ntoda03** [comment]
Hi, this is most likely  that it doesn't find any candidates. I've at least made the error message more informative. It looks like you're running with genes or domains as input. The program is meant to handle large genomic regions and input so was never tested to run like that.
